# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version

      ### - name: "Run Flutter Driver tests"
        ###run: |
          ### flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: lets_study_kitti
          baseHref: /lets_study_kitty/
